### ISSUE TITLE
Add (optional?) support for +tex_math_single_backslash extension

### ISSUE THREAD

**Issue by jez** [vim-pandoc/vim-pandoc-syntax#154]
`pandoc` supports a number of [optional syntax extensions][1], one of which I use frequently: inline math through the `\( ... \)` syntax. It'd be great if the `pandocLaTeXInlineMath` region supported this alternative syntax as well.

I tried implementing it myself:

```diff
diff --git a/syntax/pandoc.vim b/syntax/pandoc.vim
index 759ebbb..185b378 100644
--- a/syntax/pandoc.vim
+++ b/syntax/pandoc.vim
@@ -210,7 +210,7 @@ call s:WithConceal('html_c_e', 'syn match pandocHTMLCommentEnd /-->/ contained',
 " Unset current_syntax so the 2nd include will work
 unlet b:current_syntax
 syn include @LATEX syntax/tex.vim
-syn region pandocLaTeXInlineMath start=/\\\@<!\$[[:graph:]]\@=/ end=/\\\@<!\$/ keepend contains=@LATEX 
+syn region pandocLaTeXInlineMath start=/\\\@<!\(\$|\\(\)[[:graph:]]\@=/ end=/\\\@<!\(\$|\\)\)/ keepend contains=@LATEX 
 syn match pandocProtectedFromInlineLaTeX /\\\@<!\${.*}\(\(\s\|[[:punct:]]\)\([^$]*\|.*\(\\\$.*\)\{2}\)\n\n\|$\)\@=/ display
 " contains=@LATEX
 syn region pandocLaTeXMathBlock start=/\$\$/ end=/\$\$/ keepend contains=@LATEX
```

But this solution behaves weirdly with respect to cases like the following:

```
\(x$
```
where the same delimiter isn't used on both ends.

[1]: http://pandoc.org/README.html#non-pandoc-extensions

**Comment by fmoralesc** [comment]
Sorry for the late reply.

I remember not being too keen on implementing this idiom, precisely because of the issue you mentioned. Since it's redundant syntax anyway, I didn't think it was worth implementing.

Anyway, I don't have any great objection to adding support for it. I think it's best to keep it as a separate syntax rule, however, and treat the mixed ends variant as invalid (because it's insane to have it anyway).

**Comment by jez** [comment]
I didn't realize you could use two calls to `syn region xyz` to define two different regexes for the same region. I've submitted a PR.
