### ISSUE TITLE
Setting for concealcursor

### ISSUE THREAD

**Issue by jarussell** [vim-pandoc/vim-pandoc-syntax#173]
There is a setting to disable conceal entirely, but no setting to just disable concealcursor and vim-pandoc-syntax overrides whatever the default setting is for concealcursor. As far as I can tell the only way to fix it currently is to `:set concealcursor=` after the file is loaded, or add that to a syntax file in the after directory. That is inconvenient if you keep only a .vimrc and not a full .vim directory structure for multiple machines.

**Comment by fmoralesc** [comment]
Are you sure it's vim-pandoc-syntax? It doesn't touch `concealcursor` at all. Check with
~~~ vim
verbose set concealcursor?
~~~
Perhaps setting `conceallevel` overrides `concealcursor`? I'm not sure.

Instead of using a file in after, have you tried with an autocomand like this?
~~~ vim
au! Syntax pandoc setlocal concealcursor=
~~~

**Comment by jarussell** [comment]
Sorry, you're right, it's another plugin.
