### ISSUE TITLE
Syntax highlighting in code block does not work

### ISSUE THREAD

**Issue by fikovnik** [vim-pandoc/vim-pandoc-syntax#210]
Hi,

I installed the `vim-pandoc` and `vim-pandoc-syntax`. The highlighting works file, only the code blocks do not get any highlighting.
I checked the `block.pdc` file from tests and it looks like this:
![](https://www.evernote.com/shard/s15/sh/63882133-ba76-4e8e-95ae-6d5b62d3950e/4ca558ec37442541/res/2d956c3f-4b44-4ea4-b2b0-e3eef36bcb4f/skitch.png?resizeSmall&width=832)

- no highlight in the code block
- after the c code in the quote block no highlighting works

This is my vim:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 19 2017 16:43:50)
MacOS X (unix) version
Included patches: 1-172
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +find_in_path    -mouse_sysmouse  -tag_any_white
+arabic          +float           +mouse_urxvt     +tcl
+autocmd         +folding         +mouse_xterm     +termguicolors
+balloon_eval    -footer          +multi_byte      +terminfo
+browse          +fork()          +multi_lang      +termresponse
++builtin_terms  +fullscreen      -mzscheme        +textobjects
+byte_offset     -gettext         +netbeans_intg   +timers
+channel         -hangul_input    +num64           +title
+cindent         +iconv           +odbeditor       +toolbar
+clientserver    +insert_expand   +packages        +transparency
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
+file_in_path    +mouse_sgr       +tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.12_1/Frameworks -I/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/Cellar/python/2.7.12_1/Frameworks -L/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.12_1/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby
```

**Comment by jkbest2** [comment]
I am also having this problem. None of the code blocks show any highlighting, though the delimiters do collapse to the lambda and dash.

Thanks!

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  6 2017 14:13:23)
Included patches: 1-427
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl             -ebcdic          +listcmds        +persistent_undo +textobjects
+arabic          +emacs_tags      +localmap        +postscript      +timers
+autocmd         +eval            +lua/dyn         +printer         +title
-balloon_eval    +ex_extra        +menu            +profile         -toolbar
-browse          +extra_search    +mksession       +python/dyn      +user_commands
++builtin_terms  +farsi           +modify_fname    +python3/dyn     +vertsplit
+byte_offset     +file_in_path    +mouse           +quickfix        +virtualedit
+channel         +find_in_path    -mouseshape      +reltime         +visual
+cindent         +float           +mouse_dec       +rightleft       +visualextra
-clientserver    +folding         +mouse_gpm       +ruby/dyn        +viminfo
-clipboard       -footer          -mouse_jsbterm   +scrollbind      +vreplace
+cmdline_compl   +fork()          +mouse_netterm   +signs           +wildignore
+cmdline_hist    +gettext         +mouse_sgr       +smartindent     +wildmenu
+cmdline_info    -hangul_input    -mouse_sysmouse  +startuptime     +windows
+comments        +iconv           +mouse_urxvt     +statusline      +writebackup
+conceal         +insert_expand   +mouse_xterm     -sun_workshop    -X11
+cryptv          +job             +multi_byte      +syntax          -xfontset
+cscope          +jumplist        +multi_lang      +tag_binary      -xim
+cursorbind      +keymap          -mzscheme        +tag_old_static  -xpm
+cursorshape     +lambda          +netbeans_intg   -tag_any_white   -xsmp
+dialog_con      +langmap         +num64           +tcl/dyn         -xterm_clipboard
+diff            +libcall         +packages        +termguicolors   -xterm_save
+digraphs        +linebreak       +path_extra      +terminfo
-dnd             +lispindent      +perl/dyn        +termresponse
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -m
tune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1

Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynam
ic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-
common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lncurse
s -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/C
ORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/li
b  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
 -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lieee -lm
```

**Comment by alerque** [comment]
I cannot duplicate this.

What value do you have set for `g:pandoc#syntax#codeblocks#embeds#langs`?

**Comment by bpj** [comment]
FWIW I have had this issue too for a long time.  IIRC I filed an issue for it somewhere, but I can't find it now.

**Comment by alerque** [comment]
@bpj Do you still have this issue right now? If so can you report the output of these:

```vim
:echo g:pandoc#syntax#codeblocks#embeds#langs
:set ft
```

**Comment by bpj** [comment]
@alerque I don't have the issue anymore in the sense that I can get highlighting, probably because I've updated all my plugins installed via pathogen, but I still have the issue in the sense that whenever I leave and reenter a buffer all highlightings activated with `:PandocHighlight` are gone.  Is that normal?

I wish that at least all GitHub-style code blocks where the language/class is equal to a known file type would be highlighted automatically.  As a workaround I have the following in my `~/.vim/after/ftplugin/pandoc.vim`:

````vimL
fun! s:pandoc_auto_hl()
    let line=getline(line('.'))
    if line =~ '\v^\`{3,}\w\S*$' "if it looks like a GitHub style codeblock
        exe substitute(line,'\v^\`+',':PandocHighlight ','')
    endif
endfun

com! -range=% PandocAutoHighlight <line1>,<line2>call <sid>pandoc_auto_hl()
````

so now when I enter a buffer I can just execute `:PandocAutoHighlight` and most highlighting will happen automatically. The code is a bit dense, what it does is that if a line is of the general form

````markdown
```FOO
````

it converts that into `:PandocHighlight FOO` and `:execute`s that hoping for the best.

**Comment by alerque** [comment]
@bpj That sounds like a lot of unnecessary hoopla. Something isn't right because I'm seeing this working out of the box without any such hack or running any commands at all.

Can you post the output of the two commands I mentioned in [my previous comment](https://github.com/vim-pandoc/vim-pandoc-syntax/issues/210#issuecomment-484500491) so we can verify we're starting from the same place?

**Comment by bpj** [comment]
@alerque The two commands you asked for, plus another relevant
one:

| Command                                        | Output                                                                    |
| :--------------------------------------------- | :------------------------------------------------------------------------ |
| `echo g:pandoc#syntax#codeblocks#embeds#langs` | `['perl', 'yaml', 'lua', 'sh', 'html', 'css', 'javascript', 'markdown=pandoc', 'latex=tex', 'makefile=make']` |
| `set ft`                                       | `filetype=pandoc`                                                         |
| `echo g:pandoc#syntax#codeblocks#embeds#use`   | `1`                                                                       |

1.  Those languages/filetypes listed in `g:pandoc#syntax#codeblocks#embeds#langs` work as expected at all times, i.e. highlighting
    happens.
2.  I still need to use `:PandocHighlight` explicitly for languages not
    in `g:pandoc#syntax#codeblocks#embeds#langs`.
3.  It seems I don't lose highlighting set with `:PandocHighlight` quite
    everytime I reenter a buffer; *sometimes* it randomly remains.

So there may still be something strange somewhere in my `after/ftplugin/pandoc.vim` or my `.vimrc`, or in some plugin. I have run through .vimrc with `/\cpandoc` and `/\csyn` and the ftplugin with `/\csyn`, paying special attention to all autocommands, and I searched both for `g:pandoc#syntax#codeblocks#embeds#use` without finding anything suspicious-looking, but probably there is still something I do in one of those files which interferes. I discovered that I also had a `~/.vim/after/syntax/pandoc.vim` but I couldn't find anything which should affect code blocks. 

After writing the above I have also temporarily moved my whole `after` directory out of `~/.vim` and disabled all plugins except vim-pandoc-syntax but nothing changed WRT 2., however `g:pandoc#syntax#codeblocks#embeds#langs` was now an empty List as would be expected since I set it in my `after/ftplugin/pandoc.vim`.

**Comment by bpj** [comment]
@alerque I recall now what my old issue was, it was #213, and it was indeed resolved as described there. It is unrelated to this.
The value for `echo g:pandoc#syntax#codeblocks#embeds#langs` which I reported in [my last post][] had been set without reloading the file.  When I did `:edit` on a markdown/pandoc file I indeed got that E127.

Otherwise things are still as reported in my last post.

[my last post]: https://github.com/vim-pandoc/vim-pandoc-syntax/issues/210#issuecomment-484848766

**Comment by alerque** [comment]
@bpj The more I look at your results the more confident I'm becoming that you don't actually have the same problem this issue is about at all.

> Those languages/filetypes listed in `g:pandoc#syntax#codeblocks#embeds#langs` work as expected at all times, i.e. highlighting happens.

This issue ~~is~~ was about when that doesn't work, which I still don't see any evidence that it's happening to anybody any more. If @fikovnik, @jkbest2, or anybody else with _that_ issue can chime in to confirm I'd be happy to re-open this, but as far as I can tell whatever the original issue is is no longer an issue.

Your situation @bpj is something different altogether. You want buffers to remember the state of things that cannot be recreated from the contents of the file + your configuration. If everything in the `g:pandoc#syntax#codeblocks#embeds#langs` array is getting highlighted when you open a buffer, then the plugin is working as documented. If you want it to do something beyond that, please report that in another issue.

**Comment by bpj** [comment]
Den 2019-04-19 kl. 16:13, skrev Caleb Maclennan:
> Your situation @bpj is something different altogether. You want buffers to remember the state of things that cannot be recreated from the contents of the file + your configuration. If everything in the `g:pandoc#syntax#codeblocks#embeds#langs` array is getting highlighted when you open a buffer, then the plugin is working as documented. If you want it to do something beyond that, please report that in another issue.

OK.  Sorry for the noise.
