### ISSUE TITLE
Vertical grey bar showed at the left of the line numbers

### ISSUE THREAD

**Issue by andpalmier** [vim-pandoc/vim-pandoc-syntax#251]
A vertical grey bar is showed at the left of the line numbers. It happens only with files handled by vim-pandoc-syntax and even with different colorschemes.

Here are two screenshot from Kitty and Terminal.app:

<img width="813" alt="screen shot 2018-11-09 at 17 45 47" src="https://user-images.githubusercontent.com/13154679/48276082-7023b780-e447-11e8-9c6c-362110cea2fa.png">
<img width="813" alt="screen shot 2018-11-09 at 17 45 45" src="https://user-images.githubusercontent.com/13154679/48276083-7023b780-e447-11e8-915c-4fd8b29fcdec.png">

**Comment by randomizedthinking** [comment]
I though it is intentional... the grey line shows some document structure information when there is content.

**Comment by alerque** [comment]
The bar you are seeing there is not actually specific to this plugin, it is knows as a gutter (or in vim's terms, the sign column). You can disable it with `:set signcolumn=no`. It is usually set to `auto`, which means it will show up whenever code is active whenever there is a sign to display. This syntax highlighting plugin isn't the one enabling it, but [`vim-pandoc`](https://github.com/vim-pandoc/vim-pandoc) does make use of signs, so that's probably why it's showing up for you.
