### ISSUE TITLE
Tips on improving slow, laggy input mode with long soft-wrapped lines

### ISSUE THREAD

**Issue by hgvhgv** [vim-pandoc/vim-pandoc-syntax#257]
I recently switched to using soft wrapping for my main markdown writing and noticed that typing in input mode at certain points is pretty laggy, especially with very long lines (more than 2000 columns). Turning `:syn off` fixes the issue as does reformatting with hard line breaks, so it is related to both vim-pandoc-syntax and the long lines. There have been other reports of such slowness here (e.g., related to tables #137).

I'm playing around with other ways to accomplish what I like about soft wrapping with hard wrapped lines (mostly: searching across what would be hard-wrapped lines), but in the meantime: Does anyone have any tips about improving the syntax lag time in input mode with long lines? I've tried futzing with `syncolmax`, `syn sync minlines`, and `syn sync maxlines` without any success.

**Comment by fmoralesc** [comment]
I'm sorry for the performance in the soft wrapping case; I use hard wraps exclusively, so I haven't dogfooded it properly :/ 

One way to brute-force gaining performance is to comment out all the syntax that you don't need (for example, the above mentioned table support -- for example, I never use it). I've been thinking for a long while of having levels of syntax highlighting that could be configured.

The other issue related to this is that in some cases folding and autoformatting depend on syntax clues, so that might slow down things further. Those could also be disabled if needed to offset the performance loss.

**Comment by hgvhgv** [comment]
Thx for the tips, no apologies necessary---thanks for all the work on vim-pandoc (plus I believe this is the case with all syntax highlighting and long lines, and tbh the other markdown highlighting doesn't cut it for pandoc). Will report back here with any success on commenting out specific syntax, folding, or autoformatting.
