### ISSUE TITLE
Is it possible to toggle on/off highlighting for spelling?

### ISSUE THREAD

**Issue by anthrolisp** [vim-pandoc/vim-pandoc-syntax#308]
Is it possible to toggle on/off highlighting for spelling, rather than have it be defaulted to on?

**Comment by fmoralesc** [comment]
You can blacklist the spell module, and use something like [vim-uninpaired](https://github.com/tpope/vim-unimpaired)'s `yos` to toggle spell on and off.

**Comment by Jiggins** [comment]
You could also toggle spell checking completely:

```vim
set spell!
```

See `:help spell` for more info.

**Comment by alerque** [comment]
This plugin (the syntax one) only enables spelling on the Markdown syntax (basically informing VIM that it _can_ be spell checked), it does not actually enable the spell checking mode.

If you are using the [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) plugin in addition to this one, that does turn on a number of VIM features by default. You can till in not to enable spelling like this:

```vim
let g:pandoc#spell#enabled = 0
```

If not and you're using this on it's own (or if that doesn't work because it wasn't vim-pandoc than enabled spelling), my guess is you have spell checking enabled by default in your rc file. You could either set it to default off there globally or add an autocmd rule to turn it off just when you open markdown files.
