### ISSUE TITLE
LaTeX sectioning commands (\part, \section, etc.) break subsequent Markdown highlighting

### ISSUE THREAD

**Issue by RaphaelWimmer** [vim-pandoc/vim-pandoc-syntax#76]
Whenever a LaTeX sectioning command (`\part`, `\section`, ...) appears in a Markdown document, subsequent Markdown syntax is no longer being highlighted.
(Apparently, tex.vim assumes that a `\part` (etc.) syn region goes on until the next `\part` or the end of the document, and "captures" syntax highlighting from vim-pandoc-syntax.)

Example:

```
**Markdown is highlighted correctly**

\part{any sectioning command}

**Markdown is no longer highlighted correctly**
```

**Comment by jjaderberg** [comment]
I have a similar problem with a different LaTeX begin-end syntax. I use the `makeidx` LaTeX package and its `\index{}` command. This command has a particular begin-end syntax for an index entry covering a longer text portion:

>`\index{key!subkey|(}` the text, possibly `\newpage` spanning page breaks `\index{key!subkey|)}`

LaTeX  syntax is matched properly within this syntax region---called `texParen` in the syntax file shipped with my Vim---but pandoc/md syntax is not.

I work around this issue by adding a pandoc comment with a close parenthesis after the begin index command, `<!-- ) -->`. A downside is that I can then no longer jump between begin and end index command with `%`, since the syntax region now ends in my pandoc comment. This is a negligible loss for me today, but as I increase my dependency on pandoc and vim-pandoc it may become a big problem. When that happens I will try to solve it and if I succeed I will report back; for now I just want to mention it.
